I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 389, in script
    show ma shocked on top with dissolve
Exception: Image 'ma shocked' does not accept attributes 'on top'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 389, in script
    show ma shocked on top with dissolve
  File "C:\Users\Usuario\Documents\Renpy\renpy\ast.py", line 1408, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "C:\Users\Usuario\Documents\Renpy\renpy\ast.py", line 1371, in show_imspec
    renpy.config.show(name,
  File "C:\Users\Usuario\Documents\Renpy\renpy\exports.py", line 686, in show
    if not base.find_target() and renpy.config.missing_show:
  File "C:\Users\Usuario\Documents\Renpy\renpy\display\image.py", line 414, in find_target
    self.target = target._duplicate(a)
  File "C:\Users\Usuario\Documents\Renpy\renpy\display\transform.py", line 881, in _duplicate
    args.extraneous()
  File "C:\Users\Usuario\Documents\Renpy\renpy\display\core.py", line 265, in extraneous
    raise Exception("Image '{}' does not accept attributes '{}'.".format(
Exception: Image 'ma shocked' does not accept attributes 'on top'.

Windows-10-10.0.19045 AMD64
Ren'Py 8.0.3.22090809
The Working Woman's Guide to Burning Bridges 1.0
Thu Jun 29 00:15:47 2023
